{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pizza Orders",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(pizza_total{result=\"order\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Reveneue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    {
     "expr": "rate(profit_BTC_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Profit"
    }
   ]
  },
  {
   "title": "HTTP request/minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(requests_total{endpoint=\"get\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "rate(requests_total{endpoint=\"put\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "rate(requests_total{endpoint=\"post\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "rate(requests_total{endpoint=\"delete\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "sum(rate(requests_total{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(auth_total{result=\"authorized\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{result}}"
    },
    {
     "expr": "rate(auth_total{result=\"unauthorized\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "CPU and memory usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_percent{core=\"all\", source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "memory_usage_percent{type=\"RAM\", source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Pizza Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "Pizza_Latency_milliseconds{source=\"jwt-pizza-service\"}",
     "legendFormat": "Pizza Latency"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "latency_milliseconds{source=\"jwt-pizza-service\"}",
     "legendFormat": "Request latency"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "active_users_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "Active Users"
    }
   ]
  }
 ]
}